import 'tailwindcss/tailwind.css'
import Head from 'next/head';
import { MoralisProvider } from "react-moralis";
import {NotificationProvider} from "web3uikit";
import {Raffle} from '../components/Raffle.js'

export default function Home() {

  return (
    <div>
    <MoralisProvider initializeOnMount={false} >
      <NotificationProvider>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <Raffle/>
      </NotificationProvider>
      </MoralisProvider>
    </div>
  );
}
